// ISO_PasteClipboardAndReplaceSelectedLayers.jsx
// Artist: https://www.jasonfletcher.info/
// Code generated by ChatGPT-5.5
// Date: July 2, 2026
// Description: This script will paste the clipboard contents and will replace each selected layer (within the opened comp) while preserving the position, in point, and stacking order. This has only been tested with pasting a layer (footage, adjustment layer, or solid layer) since this was the original use-case. Each layer takes about 50ms, therefore 500 layers will take about 4 minutes for this script to process. There's probably a faster way to implement this but it works fine for my needs.

(function () {

    app.beginUndoGroup("Replace Selected Layers With Clipboard");

    try {

        var proj = app.project;
        if (proj === null) {
            alert("No project is open.");
            return;
        }

        var comp = proj.activeItem;
        if (!(comp instanceof CompItem)) {
            alert("Please open and activate a composition.");
            return;
        }

        if (comp.selectedLayers.length === 0) {
            alert("Please select one or more layers.");
            return;
        }

        var selectedLayers = [];
        var i;

        // Cache the selected layers so the selection can safely change.
        for (i = 0; i < comp.selectedLayers.length; i++) {
            selectedLayers.push(comp.selectedLayers[i]);
        }

        var pasteCommand = app.findMenuCommandId("Paste");

        if (pasteCommand === 0) {
            alert("Unable to locate the Paste command.");
            return;
        }

        var replacedCount = 0;
        var skippedCount = 0;

        // Process from bottom to top to avoid index shifting.
        for (i = selectedLayers.length - 1; i >= 0; i--) {

            var originalLayer = selectedLayers[i];

            if (originalLayer === null) {
                skippedCount++;
                continue;
            }

            var originalIndex = originalLayer.index;
            var originalPosition = null;

            if (originalLayer.property("Transform") !== null &&
                originalLayer.property("Transform").property("Position") !== null) {
                originalPosition = originalLayer.property("Transform").property("Position").value;
            }

            var originalInPoint = originalLayer.inPoint;
            var originalOutPoint = originalLayer.outPoint;

            // Deselect everything.
            var j;
            for (j = 1; j <= comp.numLayers; j++) {
                comp.layer(j).selected = false;
            }

            // Select only the target layer.
            originalLayer.selected = true;

            var beforeCount = comp.numLayers;

            app.executeCommand(pasteCommand);

            if (comp.numLayers <= beforeCount) {
                skippedCount++;
                originalLayer.selected = false;
                continue;
            }

            if (comp.selectedLayers.length !== 1) {
                skippedCount++;
                continue;
            }

            var newLayer = comp.selectedLayers[0];

            // Match transform.
            if (originalPosition !== null &&
                newLayer.property("Transform") !== null &&
                newLayer.property("Transform").property("Position") !== null) {

                newLayer.property("Transform").property("Position").setValue(originalPosition);
            }

            // Match timing.
            newLayer.startTime = originalInPoint;
            newLayer.inPoint = originalInPoint;
            newLayer.outPoint = originalOutPoint;

            // Match stacking order.
            while (newLayer.index > originalIndex) {
                newLayer.moveUp();
            }

            while (newLayer.index < originalIndex) {
                newLayer.moveDown();
            }

            // Remove the original layer.
            originalLayer.remove();

            replacedCount++;
        }

        alert(
            "Replace Clipboard Layers Complete\n\n" +
            "Layers replaced: " + replacedCount +
            "\nLayers skipped: " + skippedCount
        );

    } catch (err) {

        alert(
            "An error occurred:\n\n" +
            err.toString()
        );

    } finally {

        app.endUndoGroup();

    }

})();
