// ISO_SelectAlternatingLayers.jsx
// Artist: https://www.jasonfletcher.info/
// Code generated by ChatGPT-5.5 Mini
// Date: July 21, 2026
// Description: This After Effects script will select alternating layers in the active composition (skipping locked, shy, or disabled layers).

(function () {
    app.beginUndoGroup("Select Alternate Layers");

    var processedCount = 0;
    var selectedCount = 0;
    var skippedCount = 0;
    var mode = "";

    try {
        var comp = app.project.activeItem;

        if (comp === null || !(comp instanceof CompItem)) {
            alert("Error:\n\nPlease open a composition and make it active before running this script.");
            return;
        }

        var choice = prompt(
            "Select which alternating layers?\n\n" +
            "A = Layers 1, 3, 5, 7... (do not skip first layer)\n" +
            "B = Layers 2, 4, 6, 8... (skip first layer)",
            "A"
        );

        if (choice === null) {
            return;
        }

        choice = choice.toUpperCase();

        if (choice !== "A" && choice !== "B") {
            alert("Invalid selection.\n\nPlease enter either A or B.");
            return;
        }

        mode = choice;

        // Clear current selection
        for (var i = 1; i <= comp.numLayers; i++) {
            comp.layer(i).selected = false;
        }

        var startIndex = 1;

        if (choice === "B") {
            startIndex = 2;
        }

        for (var j = startIndex; j <= comp.numLayers; j += 2) {
            var layer = comp.layer(j);

            if (layer !== null) {
                processedCount++;

                // Skip locked, shy, or disabled layers
                if (layer.locked === true || layer.shy === true || layer.enabled === false) {
                    skippedCount++;
                } else {
                    layer.selected = true;
                    selectedCount++;
                }
            }
        }

        alert(
            "Select Alternate Layers Complete.\n\n" +
            "Composition: " + comp.name + "\n" +
            "Selection Mode: " + mode + "\n" +
            "Layers Checked: " + processedCount + "\n" +
            "Layers Selected: " + selectedCount + "\n" +
            "Layers Skipped: " + skippedCount
        );

    } catch (err) {
        alert("An error occurred:\n\n" + err.toString());

    } finally {
        app.endUndoGroup();
    }

})();