// ISO_PrecompSelectedLayersToSeparateComps.jsx
// Artist: https://www.jasonfletcher.info/
// Code generated by GPT-5.5
// Date: June 11, 2026
// Description: This After Effects script will precomp each selected layer into its own comp and move the newly created precomps into a folder named "Precomped via script". This script replicates the "Pre-compose: move all attributes into the new composition" technique.

(function () {
    app.beginUndoGroup("Precomp Selected Layers");

    try {
        var activeItem = app.project.activeItem;
        var selectedLayers;
        var layersToProcess;
        var targetFolder;
        var precompCount;
        var i;
        var item;

        if (!(activeItem instanceof CompItem)) {
            alert("Please open a composition and select one or more layers.");
            return;
        }

        selectedLayers = activeItem.selectedLayers;

        if (!selectedLayers || selectedLayers.length === 0) {
            alert("Please select one or more layers in the active composition.");
            return;
        }

        targetFolder = null;

        for (i = 1; i <= app.project.numItems; i++) {
            item = app.project.item(i);

            if (item instanceof FolderItem && item.name === "Precomped via script") {
                targetFolder = item;
                break;
            }
        }

        if (targetFolder === null) {
            targetFolder = app.project.items.addFolder("Precomped via script");
        }

        layersToProcess = [];

        for (i = 0; i < selectedLayers.length; i++) {
            layersToProcess.push({
                index: selectedLayers[i].index,
                name: selectedLayers[i].name
            });
        }

        layersToProcess.sort(function (a, b) {
            return b.index - a.index;
        });

        precompCount = 0;

        for (i = 0; i < layersToProcess.length; i++) {
            var precompName = layersToProcess[i].name + "_PRECOMP";
            var precompItem = activeItem.layers.precompose(
                [layersToProcess[i].index],
                precompName,
                true
            );

            if (precompItem !== null) {
                precompItem.parentFolder = targetFolder;
                precompCount++;
            }
        }

        alert(
            "Layers which were precomped: " + precompCount
        );

    } catch (err) {
        alert(
            "An error occurred:\n\n" +
            err.toString()
        );
    } finally {
        app.endUndoGroup();
    }
})();
