// Isosceles_PrecompAllSelectedComps.jsx
// Code generated by ChatGPT-5.3
// Date: March 12, 2026
// Description: This After Effects script will precomp all layers into a single precomp and move the newly created precomp into a folder named "Precomped via script". This operation will be applied to the selected comps in the Project window. This technique differs from the built-in "Pre-compose: move all attributes into the new composition" tool since this technique is entirely automated.

{
    app.beginUndoGroup("Precompose Selected Comps");

    try {

        var project = app.project;
        var selection = project.selection;

        var processedCount = 0;
        var skippedNoLayers = 0;

        // -------------------------------------------------
        // Find or create destination folder
        // -------------------------------------------------
        var folderName = "Precomped via script";
        var precompFolder = null;

        for (var f = 1; f <= project.numItems; f++) {
            var item = project.item(f);
            if (item instanceof FolderItem && item.name === folderName) {
                precompFolder = item;
                break;
            }
        }

        if (precompFolder === null) {
            precompFolder = project.items.addFolder(folderName);
        }

        // -------------------------------------------------
        // Validate selection
        // -------------------------------------------------
        if (selection.length === 0) {

            alert("Please select one or more compositions in the Project panel.");

        } else {

            for (var i = 0; i < selection.length; i++) {

                var comp = selection[i];

                if (!(comp instanceof CompItem)) {
                    continue;
                }

                if (comp.numLayers === 0) {
                    skippedNoLayers++;
                    continue;
                }

                // Build layer index array
                var layerIndices = [];
                for (var j = 1; j <= comp.numLayers; j++) {
                    layerIndices.push(j);
                }

                var newName = comp.name + "_PRECOMP";

                // -------------------------------------------------
                // Precompose and CAPTURE returned comp directly
                // -------------------------------------------------
                var createdPrecomp = comp.layers.precompose(
                    layerIndices,
                    newName,
                    true // move all attributes
                );

                // -------------------------------------------------
                // Move new comp safely (no name searching)
                // -------------------------------------------------
                if (createdPrecomp !== null && createdPrecomp instanceof CompItem) {
                    createdPrecomp.parentFolder = precompFolder;
                }

                processedCount++;
            }

            alert(
                "Comps which were precomposed: " + processedCount + "\n" +
                "Comps skipped (contained no layers): " + skippedNoLayers
            );
        }

    } catch (err) {

        alert(
            "Error: " + err.toString() +
            (err.line ? "\nLine: " + err.line : "")
        );

    } finally {

        app.endUndoGroup();
    }
}