// Isosceles_ChangeAlphaToIgnore.jsx
// Code generated by ChatGPT-4o
// Date: May 23, 2025
// Description: This After Effects script will set “Alpha: Ignore” (within the Interpret Footage window) for all the selected footage items in the Project window.

{
    var proj = app.project;
    var selectedItems = proj.selection;

    app.beginUndoGroup("Set Alpha to Ignore");

    for (var i = 0; i < selectedItems.length; i++) {
        var item = selectedItems[i];
        if (item instanceof FootageItem) {
            var interp = item.mainSource;
            if (interp instanceof FileSource) {
                interp.alphaMode = AlphaMode.IGNORE;
            }
        }
    }

    app.endUndoGroup();
}
