// Isosceles_PrecompAllSelectedComps.jsx
// Code generated by ChatGPT-5.3
// Date: March 12, 2026
// Description: This After Effects script will precomp all layers into a single precomp and move the newly created precomp into a folder named "Precomped via script". This operation will be applied to the selected comps in the Project window. This technique differs from the built-in "Pre-compose: move all attributes into the new composition" tool since this technique is entirely automated.

{
    app.beginUndoGroup("Precompose Selected Comps");

    try {

        var project = app.project;
        var selection = project.selection;

        var processedCount = 0;
        var skippedNoLayers = 0;

        // -------------------------------------------------
        // Find or create destination folder
        // -------------------------------------------------
        var precompFolder = null;
        var folderName = "Precomped via script";

        for (var f = 1; f <= project.numItems; f++) {
            if (
                project.item(f) instanceof FolderItem &&
                project.item(f).name === folderName
            ) {
                precompFolder = project.item(f);
                break;
            }
        }

        if (precompFolder === null) {
            precompFolder = project.items.addFolder(folderName);
        }

        // -------------------------------------------------
        // Validate selection
        // -------------------------------------------------
        if (selection.length === 0) {

            alert("Please select one or more compositions in the Project panel.");

        } else {

            for (var i = 0; i < selection.length; i++) {

                var item = selection[i];

                if (!(item instanceof CompItem)) {
                    continue;
                }

                var comp = item;
                var numLayers = comp.numLayers;

                if (numLayers === 0) {
                    skippedNoLayers++;
                    continue;
                }

                var layerIndices = [];

                for (var j = 1; j <= numLayers; j++) {
                    layerIndices.push(j);
                }

                var newName = comp.name + "_PRECOMP";

                // Create the precomp
                comp.layers.precompose(
                    layerIndices,
                    newName,
                    true // move all attributes
                );

                // -------------------------------------------------
                // Locate the newly created precomp and move it
                // -------------------------------------------------
                var createdPrecomp = null;

                for (var k = project.numItems; k >= 1; k--) {
                    var projItem = project.item(k);

                    if (
                        projItem instanceof CompItem &&
                        projItem.name === newName
                    ) {
                        createdPrecomp = projItem;
                        break;
                    }
                }

                if (createdPrecomp !== null) {
                    createdPrecomp.parentFolder = precompFolder;
                }

                processedCount++;
            }

            alert(
                "Comps which were precomposed: " + processedCount + "\n" +
                "Comps skipped (contained no layers): " + skippedNoLayers
            );
        }

    } catch (err) {

        alert(
            "Error: " + err.toString() +
            (err.line ? "\nLine: " + err.line : "")
        );

    } finally {

        app.endUndoGroup();

    }
}